//@version=6
indicator("CISD with Projections(Just)", shorttitle="CISD (Just)", overlay=true, max_lines_count=500, max_labels_count=500)

var string cisd_settings = "CISD Settings"

show_cisd = input.bool(true, "Show CISD", group=cisd_settings)

cisd_direction = input.string("Both", "CISD Direction", options=["Both", "Bullish Only", "Bearish Only", "None"], group=cisd_settings)
cisd_maxLines = input.int(3, "Max CISD Lines", minval=1, group=cisd_settings)


cisd_line_width = input.int(2, "Width", minval=1, inline= 'cr', group=cisd_settings)
cisd_bull_color = input.color(color.new(#5b9cf6, 0), "Bullish", inline= 'cr', group=cisd_settings)
cisd_bear_color = input.color(color.new(#f77c80, 0), "Bearish", inline= 'cr', group=cisd_settings)

show_projections = input.bool(true, "Show Projections", inline= 'pr', group=cisd_settings)
projection_levels = input.string("1,2,3,4","",inline= 'pr', group=cisd_settings)
     
     
var int market_bias = 0
var float cisd_level = na
var int cisd_start_bar = na
var float swing_pivot = na

//─────────────────────
// CISD Setup Type
//─────────────────────
type cisdSetup
    line cisdLine
    line baseLine
    array<line> projectionLines
    array<label> projection_labels
    float basePrice
    bool bullish

// Stores all active CISD setups
var array<cisdSetup> cisd_setups = array.new<cisdSetup>()


drawProjection(
    bool show,
    float cisd_level,
    float runRange,
    int direction,
    color lineColor,
    float multiplier,
    array<line> projectionLines,
    array<label> projection_labels)=>

    if show

        float level = cisd_level + direction * multiplier * runRange

        line proj = line.new(
             bar_index,
             level,
             bar_index + 2,
             level,
             color = lineColor,
             width = 1,
             style = line.style_solid)

        label lbl = label.new(
             bar_index,
             level,
             str.tostring(multiplier),
             style = label.style_label_right,
             color = color.new(lineColor, 100),
             textcolor = lineColor,
             size = size.tiny)

        array.push(projectionLines, proj)
        array.push(projection_labels, lbl)

getCurrentLegExtreme(int bias) =>
    int temp_shift = 0
    float extreme = open[0]
    int candle_type = close[0] > open[0] ? 1 : close[0] < open[0] ? -1 : 0
    if candle_type == 0 or candle_type != bias
        [extreme, bar_index]
    for i = 1 to 500
        candle_type := close[i] > open[i] ? 1 : close[i] < open[i] ? -1 : 0
        if candle_type == 0
            continue
        bool mood_match = candle_type == bias
        if not mood_match
            break
        temp_shift := i
        if bias == 1
            if open[i] < extreme
                extreme := open[i]
        else
            if open[i] > extreme
                extreme := open[i]
    int extreme_shift = na
    for k = 0 to temp_shift
        if open[k] == extreme
            extreme_shift := k
            break
    [extreme, bar_index - extreme_shift]

getPreviousLegExtreme(int bias) =>
    int i = 1
    bool artifact_found = false
    int max_shift = na
    float extreme = na
    for j = 1 to 500
        i := j
        int candle_type = close[i] > open[i] ? 1 : close[i] < open[i] ? -1 : 0
        if candle_type == 0
            continue
        bool is_correct_era = candle_type == bias
        if not artifact_found
            if is_correct_era
                artifact_found := true
                max_shift := i
                extreme := open[i]
        else
            if not is_correct_era
                break
            max_shift := i
            if bias == 1
                if open[i] < extreme
                    extreme := open[i]
            else
                if open[i] > extreme
                    extreme := open[i]
    int extreme_shift = na
    for k = 1 to max_shift
        if open[k] == extreme
            extreme_shift := k
            break
    [extreme, bar_index - extreme_shift]

if market_bias == 0 and bar_index > 10
    int has_cisd = close > open ? 1 : close < open ? -1 : 0
    if has_cisd == 0
        for k = 1 to 50
            has_cisd := close[k] > open[k] ? 1 : close[k] < open[k] ? -1 : 0
            if has_cisd != 0
                break
    if has_cisd != 0
        market_bias := has_cisd
        [origin_price, origin_time] = getCurrentLegExtreme(has_cisd)
        cisd_level := origin_price
        cisd_start_bar := origin_time
        swing_pivot := has_cisd == 1 ? high : low

int candle_type = close > open ? 1 : close < open ? -1 : 0
float current_price = na
int current_timestamp = na

if market_bias == 1
    if high > swing_pivot
        swing_pivot := high
        if candle_type == 1
            [p_price, p_idx] = getCurrentLegExtreme(1)
            current_price := p_price
            current_timestamp := p_idx
        else
            [p_price, p_idx] = getPreviousLegExtreme(1)
            current_price := p_price
            current_timestamp := p_idx
        cisd_level := current_price
        cisd_start_bar := current_timestamp

else if market_bias == -1
    if low < swing_pivot
        swing_pivot := low
        if candle_type == -1
            [p_price, p_idx] = getCurrentLegExtreme(-1)
            current_price := p_price
            current_timestamp := p_idx
        else
            [p_price, p_idx] = getPreviousLegExtreme(-1)
            current_price := p_price
            current_timestamp := p_idx
        cisd_level := current_price
        cisd_start_bar := current_timestamp

bool bias_bullish = market_bias == -1 and close > cisd_level
bool bias_bearish = market_bias == 1 and close < cisd_level

if bias_bullish or bias_bearish
    bool draw_cisd = false
    
    if cisd_direction == "Both"
        draw_cisd := true
    else if cisd_direction == "Bullish Only"
        draw_cisd := bias_bullish
    else if cisd_direction == "Bearish Only"
        draw_cisd := bias_bearish

    if draw_cisd and show_cisd
        color cisd_color = bias_bullish ? cisd_bull_color : cisd_bear_color
        color cisd_projection_color = color.new(#787B86, 0)
        
        line cisd_line = line.new(cisd_start_bar, cisd_level, bar_index, cisd_level, color=cisd_color, width=cisd_line_width, style=line.style_solid)

        float runRange = math.abs(swing_pivot - cisd_level)
        float basePrice = swing_pivot
        bool bullish = bias_bullish
        int direction = bias_bullish ? 1 : -1
        line baseLine = na

        if show_projections
            baseLine := line.new(
                bar_index,
                basePrice,
                bar_index + 3,
                basePrice,
                color = cisd_projection_color,
                width = 1,
                style = line.style_dotted)

        array<line> projections = array.new<line>()
        array<label> projection_labels = array.new<label>()

        if show_projections
            string[] values = str.split(projection_levels, ",")
            for txt in values
                float mult = str.tonumber(str.trim(txt))
                if not na(mult)
                    drawProjection(
                        true,
                        cisd_level,
                        runRange,
                        direction,
                        cisd_projection_color,
                        mult,
                        projections,
                        projection_labels)
            
        array.push(
        cisd_setups,
        cisdSetup.new(
            cisd_line,
            baseLine,
            projections,
            projection_labels,
            basePrice,
            bullish))
            
    int new_emotional_state = bias_bullish ? 1 : -1
    market_bias := new_emotional_state
    [reset_price, reset_time] = getCurrentLegExtreme(new_emotional_state)
    cisd_level := reset_price
    cisd_start_bar := reset_time
    swing_pivot := new_emotional_state == 1 ? high : low

while array.size(cisd_setups) > cisd_maxLines

    cisdSetup oldest = array.shift(cisd_setups)
    if not na(oldest.cisdLine)
        line.delete(oldest.cisdLine)

    if not na(oldest.baseLine)
        line.delete(oldest.baseLine)

    for proj in oldest.projectionLines
        line.delete(proj)
    
    for lb in oldest.projection_labels
        label.delete(lb)

int i = array.size(cisd_setups) - 1

while i >= 0
    cisdSetup setup = array.get(cisd_setups, i)
    bool touched = false

    if setup.bullish
        touched := low <= setup.basePrice
    else
        touched := high >= setup.basePrice

    if touched
        if not na(setup.cisdLine)
            line.delete(setup.cisdLine)

        if not na(setup.baseLine)
            line.delete(setup.baseLine)

        for proj in setup.projectionLines
            line.delete(proj)

        for lb in setup.projection_labels
            label.delete(lb)

        array.remove(cisd_setups, i)
    i -= 1  
